language: python

stages:
  - test

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

jobs:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial

before_install:
  - pip install codecov

install:
  - pip install pip -U
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry install -v
  - poetry build -v

script: poetry run pytest --cov=aiowhois --cov-config=.coveragerc tests/ -W ignore

after_success:
  - codecov
